## Preprocessing (second attempt)

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'. Second atttempt: also removing 'STATUS' and 'SPECIAL CONSIDERATIONS' as they are not relevant 
application_df = application_df.drop(["EIN", "NAME","SPECIAL_CONSIDERATIONS","STATUS"], axis=1)

application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [4]:
# Second attempt: Dropping column 'ASK_AMT' as it contains too many unique values
application_df = application_df.drop(columns =["ASK_AMT"])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,1
...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,0
34297,T5,Independent,C3000,ProductDev,Association,0,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,0

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
IS_SUCCESSFUL        2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_types_counts = application_df["APPLICATION_TYPE"].value_counts()
application_types_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [7]:
less_than_10 = application_types_counts[application_types_counts < 10].index
less_than_10

Index(['T25', 'T14', 'T29', 'T15', 'T17'], dtype='object', name='APPLICATION_TYPE')

In [8]:
application_df["APPLICATION_TYPE"] = application_df["APPLICATION_TYPE"].apply(lambda x: 'Other' if x in less_than_10 else x)
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ["T9","T13","T12","T2","Other"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [10]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [11]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_cleaned = classification_counts[classification_counts > 1]
classification_cleaned

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
less_than_1000 = classification_counts[classification_counts < 1000].index
less_than_1000

Index(['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object', name='CLASSIFICATION')

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df

,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,False,True,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,1,False,False,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,0,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,1,False,False,False,True,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,1,False,False,False,True,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,False,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34295,0,False,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34296,0,False,False,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34297,1,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34298,0,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [15]:
dummies_df.dtypes

IS_SUCCESSFUL                   int64
APPLICATION_TYPE_Other           bool
APPLICATION_TYPE_T10             bool
APPLICATION_TYPE_T19             bool
APPLICATION_TYPE_T3              bool
APPLICATION_TYPE_T4              bool
APPLICATION_TYPE_T5              bool
APPLICATION_TYPE_T6              bool
APPLICATION_TYPE_T7              bool
APPLICATION_TYPE_T8              bool
AFFILIATION_CompanySponsored     bool
AFFILIATION_Family/Parent        bool
AFFILIATION_Independent          bool
AFFILIATION_National             bool
AFFILIATION_Other                bool
AFFILIATION_Regional             bool
CLASSIFICATION_C1000             bool
CLASSIFICATION_C1200             bool
CLASSIFICATION_C2000             bool
CLASSIFICATION_C2100             bool
CLASSIFICATION_C3000             bool
CLASSIFICATION_Other             bool
USE_CASE_CommunityServ           bool
USE_CASE_Heathcare               bool
USE_CASE_Other                   bool
USE_CASE_Preservation            bool
USE_CASE_ProductDev              bool
ORGANIZATION_Association         bool
ORGANIZATION_Co-operative        bool
ORGANIZATION_Corporation         bool
ORGANIZATION_Trust               bool
INCOME_AMT_0                     bool
INCOME_AMT_1-9999                bool
INCOME_AMT_10000-24999           bool
INCOME_AMT_100000-499999         bool
INCOME_AMT_10M-50M               bool
INCOME_AMT_1M-5M                 bool
INCOME_AMT_25000-99999           bool
INCOME_AMT_50M+                  bool
INCOME_AMT_5M-10M                bool
dtype: object

In [16]:
# Split our preprocessed data into our features and target arrays
#  using column "IS_SUCCESSFUL" 
y = dummies_df["IS_SUCCESSFUL"].values
X = dummies_df.drop(["IS_SUCCESSFUL"], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [30]:
input_features = X_train_scaled.shape[1]
input_features

39

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  117  # # of input features tripled
hidden_nodes_layer2 = 78    # # of input features doubled
hidden_nodes_layer3 = 39    # # of input features

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 117)            │         4,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 78)             │         9,204 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            79 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,963 (54.54 KB)

 Trainable params: 13,963 (54.54 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=150)

Epoch 1/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.7094 - loss: 0.5829
Epoch 2/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7293 - loss: 0.5572
Epoch 3/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7321 - loss: 0.5515
Epoch 4/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7308 - loss: 0.5496
Epoch 5/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7285 - loss: 0.5538
Epoch 6/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7324 - loss: 0.5492
Epoch 7/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7327 - loss: 0.5463
Epoch 8/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7337 - loss: 0.5433
Epoch 9/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7327 - loss: 0.5490
Epoch 10/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7368 - loss: 0.5443
Epoch 11/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7284 - loss: 0.5471
Epoch 12/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7438 - loss: 0.5358
Epoch 13/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 15s 13ms/step - accuracy: 0.7388 - loss: 0.5382
Epoch 14/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 13ms/step - accuracy: 0.7322 - loss: 0.5476
Epoch 15/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 13ms/step - accuracy: 0.7393 - loss: 0.5397
Epoch 16/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 15ms/step - accuracy: 0.7337 - loss: 0.5437
Epoch 17/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 15ms/step - accuracy: 0.7278 - loss: 0.5517
Epoch 18/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.7375 - loss: 0.5386
Epoch 19/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 15ms/step - accuracy: 0.7366 - loss: 0.5437
Epoch 20/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 15ms/step - accuracy: 0.7297 - loss: 0.5491
Epoch 21/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 15ms/step - accuracy: 0.7333 - loss: 0.5438
Epoch 22/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - accuracy: 0.7321 - loss: 0.5477
Epoch 23/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 18s 15ms/step - accuracy: 0.7424 - loss: 0.5348
Epoch 24/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 20s 14ms/step - accuracy: 0.7398 - loss: 0.5403
Epoch 25/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 24s 17ms/step - accuracy: 0.7388 - loss: 0.5415
Epoch 26/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 17s 13ms/step - accuracy: 0.7337 - loss: 0.5443
Epoch 27/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 24s 16ms/step - accuracy: 0.7388 - loss: 0.5373
Epoch 28/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.7415 - loss: 0.5355
Epoch 29/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 14ms/step - accuracy: 0.7427 - loss: 0.5368
Epoch 30/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.7426 - loss: 0.5376
Epoch 31/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.7386 - loss: 0.5380
Epoch 32/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.7340 - loss: 0.5431
Epoch 33/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7418 - loss: 0.5346
Epoch 34/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7397 - loss: 0.5396
Epoch 35/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7353 - loss: 0.5410
Epoch 36/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7394 - loss: 0.5358
Epoch 37/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7399 - loss: 0.5385
Epoch 38/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7408 - loss: 0.5364
Epoch 39/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7408 - loss: 0.5380
Epoch 40/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7366 - loss: 0.5414
Epoch 41/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7378 - loss: 0.5382
Epoch 42/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7407 - loss: 0.5349
Epoch 43/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7370 - loss: 0.5400
Epoch 44/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.7403 - loss: 0.5379
Epoch 45/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.7430 - loss: 0.5345
Epoch 46/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7375 - loss: 0.5370
Epoch 47/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7402 - loss: 0.5376
Epoch 48/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7377 - loss: 0.5401
Epoch 49/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7427 - loss: 0.5326
Epoch 50/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7363 - loss: 0.5377
Epoch 51/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7413 - loss: 0.5348
Epoch 52/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7376 - loss: 0.5395
Epoch 53/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7395 - loss: 0.5365
Epoch 54/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7382 - loss: 0.5376
Epoch 55/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7335 - loss: 0.5409
Epoch 56/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7366 - loss: 0.5386
Epoch 57/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7392 - loss: 0.5372
Epoch 58/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7422 - loss: 0.5325
Epoch 59/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.7428 - loss: 0.5308
Epoch 60/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7386 - loss: 0.5354
Epoch 61/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7387 - loss: 0.5355
Epoch 62/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.7372 - loss: 0.5359
Epoch 63/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.7392 - loss: 0.5379
Epoch 64/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7381 - loss: 0.5367
Epoch 65/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7407 - loss: 0.5371
Epoch 66/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7441 - loss: 0.5297
Epoch 67/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7366 - loss: 0.5371
Epoch 68/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7374 - loss: 0.5349
Epoch 69/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7328 - loss: 0.5396
Epoch 70/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7385 - loss: 0.5386
Epoch 71/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7402 - loss: 0.5385
Epoch 72/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7379 - loss: 0.5369
Epoch 73/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.7370 - loss: 0.5371
Epoch 74/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7438 - loss: 0.5327
Epoch 75/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.7379 - loss: 0.5343
Epoch 76/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7383 - loss: 0.5378
Epoch 77/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7428 - loss: 0.5353
Epoch 78/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7397 - loss: 0.5345
Epoch 79/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7438 - loss: 0.5309
Epoch 80/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7421 - loss: 0.5311
Epoch 81/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7360 - loss: 0.5385
Epoch 82/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7336 - loss: 0.5395
Epoch 83/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7361 - loss: 0.5391
Epoch 84/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.7412 - loss: 0.5340
Epoch 85/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7346 - loss: 0.5380
Epoch 86/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7413 - loss: 0.5290
Epoch 87/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7414 - loss: 0.5320
Epoch 88/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7379 - loss: 0.5354
Epoch 89/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7435 - loss: 0.5321
Epoch 90/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7362 - loss: 0.5401
Epoch 91/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7412 - loss: 0.5343
Epoch 92/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7362 - loss: 0.5374
Epoch 93/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7378 - loss: 0.5349
Epoch 94/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7384 - loss: 0.5384
Epoch 95/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7364 - loss: 0.5388
Epoch 96/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7411 - loss: 0.5343
Epoch 97/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7426 - loss: 0.5296
Epoch 98/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7420 - loss: 0.5313
Epoch 99/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7401 - loss: 0.5355
Epoch 100/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7437 - loss: 0.5312
Epoch 101/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7388 - loss: 0.5364
Epoch 102/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7416 - loss: 0.5336
Epoch 103/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7435 - loss: 0.5306
Epoch 104/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7432 - loss: 0.5338
Epoch 105/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7366 - loss: 0.5370
Epoch 106/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7414 - loss: 0.5323
Epoch 107/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7410 - loss: 0.5327
Epoch 108/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7366 - loss: 0.5371
Epoch 109/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7414 - loss: 0.5315
Epoch 110/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7412 - loss: 0.5334
Epoch 111/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7396 - loss: 0.5333
Epoch 112/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7413 - loss: 0.5333
Epoch 113/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7365 - loss: 0.5372
Epoch 114/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7372 - loss: 0.5373
Epoch 115/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7398 - loss: 0.5322
Epoch 116/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7450 - loss: 0.5291
Epoch 117/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7428 - loss: 0.5304
Epoch 118/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7388 - loss: 0.5348
Epoch 119/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7395 - loss: 0.5369
Epoch 120/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7388 - loss: 0.5360
Epoch 121/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7376 - loss: 0.5319
Epoch 122/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.7360 - loss: 0.5372
Epoch 123/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7366 - loss: 0.5337
Epoch 124/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7428 - loss: 0.5304
Epoch 125/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7390 - loss: 0.5355
Epoch 126/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7457 - loss: 0.5266
Epoch 127/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7366 - loss: 0.5399
Epoch 128/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7376 - loss: 0.5389
Epoch 129/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7376 - loss: 0.5348
Epoch 130/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7476 - loss: 0.5267
Epoch 131/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7450 - loss: 0.5282
Epoch 132/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7370 - loss: 0.5376
Epoch 133/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7394 - loss: 0.5334
Epoch 134/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7347 - loss: 0.5377
Epoch 135/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7410 - loss: 0.5324
Epoch 136/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7416 - loss: 0.5287
Epoch 137/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7447 - loss: 0.5284
Epoch 138/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7441 - loss: 0.5295
Epoch 139/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.7379 - loss: 0.5373
Epoch 140/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7390 - loss: 0.5348
Epoch 141/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7408 - loss: 0.5337
Epoch 142/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 22ms/step - accuracy: 0.7398 - loss: 0.5314
Epoch 143/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 13s 12ms/step - accuracy: 0.7393 - loss: 0.5334
Epoch 144/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7456 - loss: 0.5289
Epoch 145/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7429 - loss: 0.5290
Epoch 146/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.7388 - loss: 0.5336
Epoch 147/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.7438 - loss: 0.5319
Epoch 148/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.7343 - loss: 0.5394
Epoch 149/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.7400 - loss: 0.5338
Epoch 150/150
804/804 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.7414 - loss: 0.5328

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 2s - 7ms/step - accuracy: 0.7303 - loss: 0.5768
Loss: 0.5767775774002075, Accuracy: 0.7302623987197876

In [35]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_model3.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.